### ISSUE TITLE
Reset control value when switching to velocity mode

### ISSUE THREAD

**Issue by marcantoinecouture** [sonia-auv/proc_control#10]
## Expected Behavior
Example: at [20,20] (x,y), if we switch to velocity mode, the controler should keep the current position

## Current Behavior
It goes to 20 m/s in x and y

## Possible Solution
Change the velocity to 0

**Comment by supertoto29** [comment]
@Kam0ss Still relevant?

**Comment by Kam0ss** [comment]
Not relevant anymors
