### ISSUE TITLE
Add exception handling on user input to avoid future problem with the script. Also create the correct folder if it dosen't exist.

### ISSUE THREAD

**Issue by Kam0ss** [sonia-auv/proc_control#9]
maybe you should add exception handling on user input to avoid future problem with the script. Also create the correct folder if it dosen't exist.

_Originally posted by @0x72D0 in https://github.com/sonia-auv/proc_control/issues/8#issuecomment-589954899_

**Comment by alexemdesgagne** [comment]
I migrated to a Flexbe behavior.
